package com.resq

object Str {
    val it = mapOf(
        "Rescue surplus. Support people. Reduce waste." to "Salva le eccedenze. Aiuta le persone. Riduci gli sprechi.",
        "AI-powered platform that safely matches surplus food and essentials with people and organizations who need them." to "Piattaforma basata sull'IA che collega in sicurezza cibo e beni in eccedenza con persone e organizzazioni che ne hanno bisogno.",
        "Get Started" to "Inizia",
        "Choose how you want to help" to "Scegli come vuoi aiutare",
        "I need support" to "Ho bisogno di aiuto",
        "Get matched with safe nearby offers" to "Ricevi offerte sicure vicino a te",
        "I want to donate" to "Voglio donare",
        "Share surplus food and essentials" to "Condividi cibo e beni in eccedenza",
        "I represent an organization" to "Rappresento un'organizzazione",
        "Receive and route donations" to "Ricevi e smista le donazioni",
        "Continue" to "Continua",
        "We protect recipient privacy and check food safety before matching." to "Proteggiamo la privacy dei beneficiari e verifichiamo la sicurezza alimentare prima dell'abbinamento.",
        "Language" to "Lingua",

        "Set up your profile" to "Configura il tuo profilo",
        "Account type" to "Tipo di account",
        "Donor type" to "Tipo di donatore",
        "Organization type" to "Tipo di organizzazione",
        "Individual" to "Privato",
        "Family" to "Famiglia",
        "Student" to "Studente",
        "Elderly person" to "Anziano",
        "Nonprofit" to "No-profit",
        "Restaurant" to "Ristorante",
        "Cafe" to "Caffè",
        "Grocery store" to "Negozio di alimentari",
        "School" to "Scuola",
        "University" to "Università",
        "Office" to "Ufficio",
        "Event organizer" to "Organizzatore eventi",
        "Shelter" to "Rifugio",
        "Food bank" to "Banco alimentare",
        "Community center" to "Centro comunitario",
        "Student pantry" to "Dispensa studenti",
        "Volunteer group" to "Gruppo di volontari",
        "Name" to "Nome",
        "Display name" to "Nome visualizzato",
        "Organization name" to "Nome organizzazione",
        "Location / area" to "Luogo / zona",
        "Pickup radius (km)" to "Raggio di ritiro (km)",
        "What do you need" to "Di cosa hai bisogno",
        "Dietary restrictions" to "Restrizioni alimentari",
        "Availability" to "Disponibilità",
        "Urgency" to "Urgenza",
        "What can you accept" to "Cosa puoi accettare",
        "Max pickup distance (km)" to "Distanza max di ritiro (km)",
        "Daily capacity (meals)" to "Capacità giornaliera (pasti)",
        "Save and continue" to "Salva e continua",

        "Welcome back" to "Bentornato",
        "Share surplus, reduce waste." to "Condividi le eccedenze, riduci gli sprechi.",
        "Create new donation" to "Crea una nuova donazione",
        "Meals" to "Pasti",
        "Rescued" to "Salvato",
        "CO2 avoided" to "CO2 evitata",
        "High demand near you: ready-to-eat meals, hygiene kits, baby items." to "Alta richiesta vicino a te: pasti pronti, kit per l'igiene, articoli per bambini.",
        "Active donations" to "Donazioni attive",
        "No donations yet" to "Ancora nessuna donazione",
        "View details" to "Dettagli",

        "Create donation" to "Crea donazione",
        "AI-assisted safety check. Requires human confirmation. Follow local food safety rules." to "Controllo di sicurezza assistito dall'IA. Richiede conferma umana. Rispetta le norme locali sulla sicurezza alimentare.",
        "Upload photo" to "Carica foto",
        "Quantity" to "Quantità",
        "Storage / condition" to "Conservazione / condizione",
        "Storage temp" to "Temperatura di conservazione",
        "Pickup window" to "Finestra di ritiro",
        "Notes (optional)" to "Note (facoltativo)",
        "Analyze with AI" to "Analizza con l'IA",
        "Category" to "Categoria",
        "Food" to "Cibo",
        "Clothes" to "Vestiti",
        "Hygiene" to "Igiene",
        "Baby" to "Bambini",
        "Other" to "Altro",

        "AI is checking item type, safety, and best matches..." to "L'IA controlla tipo, sicurezza e migliori abbinamenti...",
        "Detected item" to "Articolo rilevato",
        "AI-generated listing" to "Annuncio generato dall'IA",
        "Safety status" to "Stato di sicurezza",
        "Risk score" to "Punteggio di rischio",
        "Risk score: " to "Punteggio di rischio: ",
        "Why this result?" to "Perché questo risultato?",
        "Checklist" to "Checklist",
        "AI needs confirmation" to "L'IA chiede conferma",
        "Recommended recipients" to "Beneficiari consigliati",
        "Edit listing" to "Modifica",
        "Find matches" to "Trova abbinamenti",
        "Save as draft" to "Salva come bozza",
        "Safe" to "Sicuro",
        "Donate soon" to "Dona presto",
        "Organization-only" to "Solo organizzazioni",
        "Needs review" to "Da verificare",
        "Not safe" to "Non sicuro",
        "Recycle" to "Riciclo",

        "match" to "abbinamento",
        "km away" to "km da te",
        "Donation #" to "Donazione n.",
        "Top matches" to "Migliori abbinamenti",
        "Perishable food is routed to organizations first." to "Il cibo deperibile va prima alle organizzazioni.",
        "No matches yet" to "Ancora nessun abbinamento",
        "Send offer" to "Invia offerta",

        "Matched" to "Abbinato",
        "Mark matched" to "Segna come abbinato",
        "Mark picked up" to "Segna come ritirato",
        "Mark completed" to "Segna come completato",
        "Back to home" to "Torna alla home",
        "Nothing here" to "Niente qui",
        "ResQShare AI does not replace local food safety regulations. Donors verify safety before distribution." to "ResQShare AI non sostituisce le normative locali sulla sicurezza alimentare. I donatori verificano la sicurezza prima della distribuzione.",

        "Hi, here are safe offers near you" to "Ciao, ecco offerte sicure vicino a te",
        "We protect recipient privacy. Food safety is checked before matching." to "Proteggiamo la privacy dei beneficiari. La sicurezza alimentare è verificata prima dell'abbinamento.",
        "All" to "Tutti",
        "No offers right now" to "Nessuna offerta al momento",
        "Safety checked" to "Sicurezza verificata",
        "Request" to "Richiedi",

        "Create request" to "Crea richiesta",
        "AI improves your request privately. No public photos or personal documents needed." to "L'IA migliora la tua richiesta in privato. Non servono foto pubbliche o documenti personali.",
        "Request submitted" to "Richiesta inviata",
        "AI created a private structured request and will match you with safe offers." to "L'IA ha creato una richiesta privata e strutturata e ti abbinerà a offerte sicure.",
        "Done" to "Fatto",
        "Quantity / family size" to "Quantità / dimensione famiglia",
        "Submit request" to "Invia richiesta",
        "Morning" to "Mattina",
        "Afternoon" to "Pomeriggio",
        "Evening" to "Sera",
        "Weekend" to "Weekend",

        "Your matches" to "I tuoi abbinamenti",
        "No requests yet" to "Ancora nessuna richiesta",

        "Organization dashboard" to "Pannello organizzazione",
        "Incoming offers" to "Offerte in arrivo",
        "No incoming offers" to "Nessuna offerta in arrivo",
        "Accept" to "Accetta",
        "Decline" to "Rifiuta",
        "Needs overview" to "Panoramica dei bisogni",
        "Meals needed" to "Pasti necessari",
        "Hygiene kits" to "Kit per l'igiene",
        "High priority" to "Alta priorità",
        "3 food donations expire within 2 hours" to "3 donazioni di cibo scadono entro 2 ore",
        "High demand for baby items in your area" to "Alta richiesta di articoli per bambini nella tua zona",

        "Map" to "Mappa",
        "Fresh bread - safe" to "Pane fresco - sicuro",
        "Sandwiches - urgent pickup" to "Panini - ritiro urgente",
        "Prepared meal - needs review" to "Pasto pronto - da verificare",
        "Hope Shelter" to "Rifugio Hope",
        "Urgent" to "Urgente",
        "Review" to "Verifica",
        "Organization" to "Organizzazione",

        "Impact dashboard" to "Pannello d'impatto",
        "Food rescued" to "Cibo salvato",
        "Meals provided" to "Pasti forniti",
        "Items reused" to "Oggetti riutilizzati",
        "People helped" to "Persone aiutate",
        "Organizations" to "Organizzazioni",
        "Every completed match reduces waste and supports people nearby." to "Ogni abbinamento completato riduce gli sprechi e aiuta le persone vicine.",
        "ResQShare AI does not replace local food safety regulations." to "ResQShare AI non sostituisce le normative locali sulla sicurezza alimentare.",

        "Profile" to "Profilo",
        "Role" to "Ruolo",
        "Privacy & safety" to "Privacy e sicurezza",
        "We protect recipient privacy." to "Proteggiamo la privacy dei beneficiari.",
        "Do not share sensitive personal documents." to "Non condividere documenti personali sensibili.",
        "Food safety is AI-assisted and requires human confirmation." to "La sicurezza alimentare è assistita dall'IA e richiede conferma umana.",
        "ResQShare AI does not replace local food safety regulations. Donors and organizations are responsible for verifying food safety before distribution." to "ResQShare AI non sostituisce le normative locali sulla sicurezza alimentare. Donatori e organizzazioni sono responsabili della verifica prima della distribuzione.",
        "Switch role" to "Cambia ruolo",

        "Account" to "Account",
        "Email" to "Email",
        "Password" to "Password",
        "Log in" to "Accedi",
        "Log in to your account." to "Accedi al tuo account.",
        "I already have an account" to "Ho già un account",

        "Share extra food and essentials with people nearby who need them." to "Condividi cibo e beni in più con le persone vicine che ne hanno bisogno.",
        "More" to "Altri",
        "Less" to "Meno",
        "Or write your own" to "Oppure scrivi la tua",
        "Tap to upload a photo" to "Tocca per caricare una foto",
        "Tap to change photo" to "Tocca per cambiare foto",
        "Pick date" to "Scegli data",
        "Pick time" to "Scegli ora",
        "Add a photo and a few details." to "Aggiungi una foto e qualche dettaglio.",
        "Condition" to "Condizione",
        "Pickup time" to "Orario di ritiro",
        "Location" to "Luogo",
        "Tap the map to set a point" to "Tocca la mappa per impostare un punto",
        "Tap to open the map" to "Tocca per aprire la mappa",
        "Detect automatically" to "Rileva automaticamente",
        "People" to "Persone",
        "Partners" to "Partner",
        "Your badges" to "I tuoi badge",
        "First share" to "Prima condivisione",
        "100 meals" to "100 pasti",
        "50 kg saved" to "50 kg salvati",
        "50 people" to "50 persone",
        "5 partners" to "5 partner",
        "100kg CO2" to "100kg CO2",
        "Log out" to "Esci",
        "Your account" to "Il tuo account",
        "Guest" to "Ospite",
        "Preferences" to "Preferenze",
        "Notifications" to "Notifiche",
        "Sound" to "Suono",
        "Show nearby alerts" to "Mostra avvisi vicini",
        "Edit profile" to "Modifica profilo",
        "My badges" to "I miei badge",
        "Saved places" to "Luoghi salvati",
        "Help & FAQ" to "Aiuto e FAQ",
        "Rate the app" to "Valuta l'app",
        "About ResQShare" to "Informazioni su ResQShare",
        "Terms & policies" to "Termini e politiche",
        "Support" to "Supporto",
        "Admin panel" to "Pannello admin",
        "Platform overview" to "Panoramica della piattaforma",
        "Accounts" to "Account",
        "Donations" to "Donazioni",
        "Donors" to "Donatori",
        "Recipients" to "Beneficiari",
        "Orgs" to "Org.",
        "All accounts" to "Tutti gli account",
        "No accounts" to "Nessun account",
        "Step" to "Passo",
        "Next" to "Avanti",
        "Create account" to "Crea account",
        "Tell us about you" to "Parlaci di te",
        "Where are you?" to "Dove ti trovi?",
        "Set your location on the map." to "Imposta la tua posizione sulla mappa.",
        "Create your account" to "Crea il tuo account",
        "You can log in with these later." to "Potrai accedere con questi dati più tardi.",
        "Info for AI" to "Info per l'IA",
        "Anything that helps the AI write the listing" to "Qualcosa che aiuti l'IA a scrivere l'annuncio",
        "Post listing" to "Pubblica annuncio",
        "Message" to "Scrivi",
        "Message donor" to "Scrivi al donatore",
        "Donor" to "Donatore",
        "Messages" to "Messaggi",
        "Your conversations." to "Le tue conversazioni.",
        "No messages yet" to "Ancora nessun messaggio",
        "User" to "Utente",
        "Say hello" to "Saluta",
        "Type a message" to "Scrivi un messaggio",
        "Bakery" to "Panetteria",
        "Hotel" to "Hotel",
        "Canteen" to "Mensa",
        "Supermarket" to "Supermercato",
        "Farm" to "Fattoria",
        "Church" to "Chiesa",
        "Charity" to "Associazione benefica",
        "Hospital" to "Ospedale",
        "Library" to "Biblioteca",
        "Refugee" to "Rifugiato",
        "Veteran" to "Veterano",
        "Single parent" to "Genitore single",
        "Toys" to "Giocattoli",
        "Books" to "Libri",
        "Furniture" to "Mobili",
        "Electronics" to "Elettronica",
        "Medicine" to "Medicine",
        "Household" to "Casa",
        "Shoes" to "Scarpe",
        "Blankets" to "Coperte",
        "Diapers" to "Pannolini",
        "Water" to "Acqua",
        "Toiletries" to "Articoli da toeletta",
        "Homeless" to "Senzatetto",
        "Disabled" to "Disabile",
        "Mosque" to "Moschea",
        "Red Cross" to "Croce Rossa",

        "Let's get started" to "Iniziamo",
        "What describes you best?" to "Cosa ti descrive meglio?",
        "A bit about you" to "Qualcosa su di te",
        "This stays private." to "Questo resta privato.",
        "About your organization" to "Sulla tua organizzazione",
        "About your business" to "Sulla tua attività",
        "What do you need?" to "Di cosa hai bisogno?",
        "Pick everything that applies." to "Seleziona tutto ciò che si applica.",
        "I need" to "Ho bisogno di",
        "How urgent is it?" to "Quanto è urgente?",
        "What can you accept?" to "Cosa puoi accettare?",
        "We accept" to "Accettiamo",
        "What do you usually share?" to "Cosa condividi di solito?",

        "Can't reach the server" to "Impossibile raggiungere il server",
        "Something went wrong" to "Qualcosa è andato storto",
        "Enter a valid email" to "Inserisci un'email valida",
        "Password must be at least 6 characters" to "La password deve avere almeno 6 caratteri",
        "Invalid email address" to "Indirizzo email non valido",
        "Email already registered" to "Email già registrata",
        "No account found" to "Nessun account trovato",
        "Wrong password" to "Password errata",
        "Email and password required" to "Email e password obbligatorie",

        "What would you like to do?" to "Cosa vuoi fare?",
        "I need help" to "Ho bisogno di aiuto",
        "I want to give" to "Voglio donare",
        "Receive food and essentials nearby" to "Ricevi cibo e beni essenziali vicino a te",
        "Share your surplus with people nearby" to "Condividi le tue eccedenze con le persone vicine",
        "About you" to "Su di te",
        "What kind of donor are you?" to "Che tipo di donatore sei?",
        "Who are you?" to "Chi sei?",
        "A person or an organization?" to "Una persona o un'organizzazione?",
        "A person" to "Una persona",
        "An organization" to "Un'organizzazione",
        "I am a" to "Sono un",
        "I share" to "Condivido",
        "Confirm password" to "Conferma password",
        "Passwords don't match" to "Le password non coincidono",
        "Manage the platform" to "Gestisci la piattaforma",
        "Delete" to "Elimina",
        "Ban" to "Blocca",
        "Unban" to "Sblocca",
        "Banned" to "Bloccato",

        "Large family" to "Famiglia numerosa",
        "Disabled person" to "Persona con disabilità",
        "Unemployed" to "Disoccupato",
        "Low-income" to "Basso reddito",
        "Pensioner" to "Pensionato",
        "Orphan" to "Orfano",
        "Caregiver" to "Caregiver",
        "Immigrant" to "Immigrato",
        "Abuse survivor" to "Sopravvissuto a violenze",
        "Foster family" to "Famiglia affidataria",
        "Widow" to "Vedovo/a",
        "Chronically ill" to "Malato cronico",
        "Pregnant" to "In gravidanza",
        "Migrant worker" to "Lavoratore migrante",
        "Ex-offender" to "Ex detenuto",
        "Synagogue" to "Sinagoga",
        "Orphanage" to "Orfanotrofio",
        "Nursing home" to "Casa di riposo",
        "NGO" to "ONG",
        "Refugee center" to "Centro per rifugiati",
        "Rehab center" to "Centro di riabilitazione",
        "Animal shelter" to "Rifugio per animali",
        "Youth center" to "Centro giovanile",
        "Women's shelter" to "Casa rifugio per donne",
        "Crisis center" to "Centro di crisi",
        "Hospice" to "Hospice",
        "Disability center" to "Centro per disabili",
        "Catering" to "Catering",
        "Food producer" to "Produttore alimentare",
        "Distributor" to "Distributore",
        "Hostel" to "Ostello",
        "Coffee shop" to "Caffetteria",
        "Pizzeria" to "Pizzeria",
        "Butcher" to "Macelleria",
        "Greengrocer" to "Fruttivendolo",
        "Market stall" to "Bancarella del mercato",
        "Deli" to "Gastronomia",
        "Brewery" to "Birrificio",
        "Food truck" to "Food truck",
        "Wholesaler" to "Grossista",
        "Convenience store" to "Minimarket",
        "Kindergarten" to "Asilo",
        "Formula" to "Latte in formula",
        "First aid" to "Pronto soccorso",
        "Cleaning" to "Prodotti per la pulizia",
        "Pet food" to "Cibo per animali",
        "Kitchenware" to "Articoli da cucina",
        "Tools" to "Attrezzi",
        "Stationery" to "Cancelleria",
        "Winter gear" to "Abbigliamento invernale",
        "Backpacks" to "Zaini",
        "Sanitary" to "Prodotti sanitari",
        "Eyewear" to "Occhiali",
        "Heaters" to "Stufe",
        "Towels" to "Asciugamani",
        "Bedding" to "Biancheria da letto",
        "Appliances" to "Elettrodomestici",
        "Drafts" to "Bozze",
        "Draft" to "Bozza",
        "Resume" to "Riprendi",
        "Untitled draft" to "Bozza senza titolo",
        "You might need this" to "Potrebbe servirti",
        "More filters" to "Altri filtri",
        "Delivery available" to "Consegna disponibile",
        "Within my radius" to "Nel mio raggio",
        "Reset filters" to "Reimposta filtri",
        "offers" to "offerte",
        "About the donor" to "Sul donatore",
        "Area" to "Zona",
        "Our mission" to "La nostra missione",
        "Version" to "Versione",
        "Using the service" to "Uso del servizio",
        "Food safety" to "Sicurezza alimentare",
        "Respect" to "Rispetto",
        "Your location" to "La tua posizione",
        "Your data" to "I tuoi dati",
        "Staying safe" to "Restare al sicuro",
        "Save changes" to "Salva modifiche",
        "My area" to "La mia zona",
        "My location" to "La mia posizione",
        "Requests near you" to "Richieste vicino a te",
        "Request sent" to "Richiesta inviata",
        "Your request is now visible to donors near you. They can message you to offer help." to "La tua richiesta ora è visibile ai donatori vicino a te. Possono scriverti per offrire aiuto.",
        "When are you free to receive" to "Quando puoi ricevere",
        "My requests" to "Le mie richieste",
        "What you are asking for." to "Cosa stai chiedendo.",
        "You have no active requests" to "Non hai richieste attive",
        "Fulfilled" to "Completata",
        "Cancel request" to "Annulla richiesta",
        "See what people need and offer help." to "Guarda di cosa hanno bisogno le persone e offri aiuto.",
        "No requests nearby" to "Nessuna richiesta nelle vicinanze",
        "Requests" to "Richieste",
        "Your name" to "Il tuo nome",
        "Max pickup radius (km)" to "Raggio max di ritiro (km)",
        "Max radius (km)" to "Raggio max (km)",
        "Your rating" to "La tua valutazione",
        "Comment" to "Commento",
        "Send rating" to "Invia valutazione",
        "App rating" to "Valutazione app",
        "ratings" to "valutazioni",
        "Options" to "Opzioni",
        "Sort" to "Ordina",
        "Tell recipients who you are (e.g. a small bakery)" to "Di' ai beneficiari chi sei (es. una piccola panetteria)",
        "How far around your point people can collect." to "Quanto lontano dal tuo punto le persone possono ritirare.",
        "Pick a category" to "Scegli una categoria",
        "Add at least one photo" to "Aggiungi almeno una foto",
        "Thank you for sharing!" to "Grazie per aver condiviso!",
        "Here is the impact you just made:" to "Ecco l'impatto che hai appena avuto:",
        "Add photos" to "Aggiungi foto",
        "At least one photo is required. You can add several." to "È richiesta almeno una foto. Puoi aggiungerne diverse.",
        "Available" to "Disponibile",
        "Reserved" to "Prenotato",
        "Given away" to "Donato",
        "Sent" to "Inviato",
        "Under review" to "In revisione",
        "Cancelled" to "Annullato",
        "Mark reserved" to "Segna come prenotato",
        "Mark given away" to "Segna come donato",
        "Mark cancelled" to "Segna come annullato",
        "Archive" to "Archivio",
        "My donations" to "Le mie donazioni",
        "Active" to "Attive",
        "Search" to "Cerca",
        "Restore to active" to "Ripristina tra le attive",
        "Cancel reservation" to "Annulla prenotazione",
        "This listing is in your archive." to "Questo annuncio è nel tuo archivio.",
        "Answer the checklist to continue." to "Rispondi alla checklist per continuare.",
        "Delivery radius (km)" to "Raggio di consegna (km)",
        "How far you are willing to deliver." to "Fin dove sei disposto a consegnare.",
        "Recipient" to "Beneficiario",
        "Test data" to "Dati di prova",
        "Reviews" to "Recensioni",
        "Create and manage rewards." to "Crea e gestisci i premi.",
        "All rewards" to "Tutti i premi",
        "Emoji (type your own)" to "Emoji (scrivi la tua)",
        "All listings on the platform." to "Tutti gli annunci della piattaforma.",
        "Everyone on the platform." to "Tutti gli utenti della piattaforma.",
        "needs" to "serve",
        "urgent" to "urgente",
        "accepts this category" to "accetta questa categoria",
        "general intake" to "raccolta generale",
        "Reserved keeps it active. Given away and Cancelled move it to your archive." to "«Prenotato» lo mantiene attivo. «Donato» e «Annullato» lo spostano nell'archivio.",
        "Add info for the AI" to "Aggiungi info per l'IA",
        "Choose pickup or delivery" to "Scegli ritiro o consegna",
        "Newest" to "Più recenti",
        "Oldest" to "Meno recenti",
        "Tap a badge to see how to unlock it." to "Tocca un badge per vedere come sbloccarlo.",
        "Requirement" to "Requisito",
        "Reach" to "Raggiungi",
        "Gift" to "Regalo",
        "Unlocked" to "Sbloccato",
        "Locked" to "Bloccato",
        "Close" to "Chiudi",
        "to go" to "rimanenti",
        "Description" to "Descrizione",
        "What it is and how to earn it" to "Cos'è e come ottenerlo",
        "people helped" to "persone aiutate",
        "kg rescued" to "kg salvati",
        "kg CO2 avoided" to "kg CO₂ evitati",
        "items reused" to "oggetti riutilizzati",
        "partner organizations" to "organizzazioni partner",
        "meals provided" to "pasti forniti",
        "Getting started" to "Primi passi",
        "Helping hands" to "Mani d'aiuto",
        "Eco saver" to "Eco-risparmiatore",
        "Climate hero" to "Eroe del clima",
        "Reuse champion" to "Campione del riuso",
        "Cinema pass" to "Biglietto del cinema",
        "Grocery card" to "Carta spesa",
        "Make your very first donation and start your journey of giving." to "Fai la tua primissima donazione e inizia il tuo percorso di generosità.",
        "Provide 10 meals to people in your community." to "Fornisci 10 pasti alle persone della tua comunità.",
        "Reach 100 meals shared — a real difference for many tables." to "Raggiungi 100 pasti condivisi — una vera differenza per molte tavole.",
        "Help 25 different people through your donations." to "Aiuta 25 persone diverse con le tue donazioni.",
        "Support 50 people across the city with what you share." to "Sostieni 50 persone in città con ciò che condividi.",
        "Rescue 50 kg of food and goods from going to waste." to "Salva 50 kg di cibo e beni dallo spreco.",
        "Prevent 100 kg of CO₂ emissions by reusing instead of trashing." to "Previeni 100 kg di emissioni di CO₂ riutilizzando invece di buttare.",
        "Give 50 individual items a useful second life." to "Dai a 50 oggetti una seconda vita utile.",
        "Collaborate with 5 partner organizations in the network." to "Collabora con 5 organizzazioni partner della rete.",
        "Provide 200 meals to unlock a free coffee at any partner café." to "Fornisci 200 pasti per sbloccare un caffè gratis in qualsiasi bar partner.",
        "Help 100 people to earn 2 cinema tickets from our partners." to "Aiuta 100 persone per ottenere 2 biglietti del cinema dai nostri partner.",
        "Rescue 100 kg of goods to receive a $20 grocery gift card." to "Salva 100 kg di beni per ricevere una carta spesa da 20 $.",
        "Free coffee at partner cafés" to "Caffè gratis nei bar partner",
        "2 cinema tickets" to "2 biglietti del cinema",
        "$20 grocery gift card" to "Carta spesa da 20 $",
        "Your gifts" to "I tuoi regali",
        "Add a photo" to "Aggiungi una foto",
        "A clear photo helps the AI." to "Una foto nitida aiuta l'IA.",
        "What is it?" to "Cos'è?",
        "Pick a category." to "Scegli una categoria.",
        "Tell us more about it." to "Raccontaci di più.",
        "Choose one or both." to "Scegli una o entrambe.",
        "Pickup" to "Ritiro",
        "Where can it be collected?" to "Dove può essere ritirato?",
        "Create reward" to "Crea premio",
        "Title" to "Titolo",
        "Emoji" to "Emoji",
        "Goal metric" to "Metrica obiettivo",
        "Goal" to "Obiettivo",
        "Gift (optional)" to "Regalo (facoltativo)",
        "50 people helped" to "50 persone aiutate",
        "50 kg rescued" to "50 kg salvati",
        "Coffee voucher" to "Buono caffè",
        "Free coffee at partner cafes" to "Caffè gratis nei bar partner",

        "AVAIL" to "Disponibile",
        "SENT" to "Inviato",
        "REVIEW" to "In revisione",
        "DONE" to "Completato",
        "MATCH" to "Abbinato",
        "PICKED" to "Ritirato",
        "LOW" to "Bassa",
        "MED" to "Media",
        "HIGH" to "Alta",

        "Hi" to "Ciao",
        "Hi there" to "Ciao",
        "Share what you no longer need." to "Condividi ciò che non ti serve più.",
        "How will it reach people?" to "Come arriverà alle persone?",
        "Pickup only" to "Solo ritiro",
        "I can deliver" to "Posso consegnare",
        "Delivery time window" to "Finestra di consegna",
        "Delivery" to "Consegna",
        "Describe the item so the AI can write the listing" to "Descrivi l'oggetto così l'IA può scrivere l'annuncio",
        "Enter a quantity" to "Inserisci una quantità",
        "Set a location on the map" to "Imposta un punto sulla mappa",
        "Set a time" to "Imposta un orario",
        "Safety checklist" to "Checklist di sicurezza",
        "Confirm each point before sharing." to "Conferma ogni punto prima di condividere.",
        "Yes" to "Sì",
        "No" to "No",
        "Your point must be within the USA" to "Il punto deve trovarsi negli USA",
        "How it works" to "Come funziona",
        "Every completed donation counts toward your badges." to "Ogni donazione completata conta per i tuoi badge.",
        "Help more people to unlock higher rewards." to "Aiuta più persone per sbloccare premi maggiori.",
        "Organizations multiply your impact across the city." to "Le organizzazioni moltiplicano il tuo impatto in città.",
        "OK" to "OK",
        "Your area" to "La tua zona",
        "To change your details, contact support." to "Per modificare i tuoi dati, contatta il supporto.",
        "We never share your exact address. Recipients see only your area and what you offer. Food safety is your responsibility before handover." to "Non mostriamo mai il tuo indirizzo esatto. I beneficiari vedono solo la tua zona e ciò che offri. La sicurezza alimentare è tua responsabilità prima della consegna.",
        "Is it free? Yes, completely. How do I give? Create a donation and the AI builds the listing. How do people reach me? Through the in-app chat." to "È gratis? Sì, completamente. Come dono? Crea una donazione e l'IA crea l'annuncio. Come mi contattano? Tramite la chat nell'app.",
        "Thanks for using ResQShare! We hope it helps your community." to "Grazie per aver usato ResQShare! Speriamo aiuti la tua comunità.",
        "ResQShare safely redistributes surplus food and essentials to people nearby. Version 1.0." to "ResQShare ridistribuisce in sicurezza cibo e beni in eccedenza alle persone vicine. Versione 1.0.",
        "By using ResQShare you agree to provide accurate information and to follow local food-safety rules before any handover." to "Usando ResQShare accetti di fornire informazioni accurate e di rispettare le norme locali sulla sicurezza alimentare prima di ogni consegna.",

        "Who do you want to help?" to "Chi vuoi aiutare?",
        "Pick your role to get started." to "Scegli il tuo ruolo per iniziare.",
        "AI checks food safety before every match." to "L'IA verifica la sicurezza alimentare prima di ogni abbinamento.",
        "We protect recipient privacy at all times." to "Proteggiamo sempre la privacy dei beneficiari.",
        "Smart matching connects surplus to need fast." to "L'abbinamento intelligente collega rapidamente le eccedenze ai bisogni.",
        "Tell us what you're sharing." to "Dicci cosa stai condividendo.",
        "Tell us what you need." to "Dicci di cosa hai bisogno.",
        "Details" to "Dettagli",
        "Update status" to "Aggiorna stato",
        "Best places for your donation." to "I posti migliori per la tua donazione.",
        "We'll match you with safe offers." to "Ti abbineremo a offerte sicure.",
        "Safe offers near you" to "Offerte sicure vicino a te",
        "Browse and request what you need." to "Sfoglia e richiedi ciò di cui hai bisogno.",
        "Requests you've submitted." to "Le richieste che hai inviato.",
        "Your settings and safety info." to "Le tue impostazioni e info sulla sicurezza.",
        "Offers, needs and priorities." to "Offerte, bisogni e priorità.",
        "Accept or decline donations." to "Accetta o rifiuta le donazioni.",
        "Nearby offers and organizations." to "Offerte e organizzazioni vicine.",
        "What we've achieved together." to "Cosa abbiamo ottenuto insieme.",

        "Home" to "Home",
        "Matches" to "Abbinamenti",
        "Create" to "Crea",
        "Impact" to "Impatto",
        "Dashboard" to "Pannello",
        "Incoming" to "In arrivo",

        "AI is analyzing the photo..." to "Sto analizzando la foto...",
        "Done! We filled in the details — just look them over." to "Fatto! Abbiamo compilato i dettagli — dai un'occhiata.",
        "Edit the text before you publish." to "Modifica il testo prima di pubblicare.",
        "Review your request" to "Controlla la tua richiesta",
        "AI wrote this announcement." to "L'IA ha scritto questo annuncio.",
        "Announcement" to "Annuncio",
        "Publish request" to "Pubblica richiesta",
        "Generating..." to "Generazione...",
        "Who fulfilled this request?" to "Chi ha soddisfatto questa richiesta?",
        "They get the AI-credited impact for it." to "Riceveranno l'impatto valutato dall'IA.",
        "No conversations yet. Close without crediting." to "Ancora nessuna conversazione. Chiudi senza assegnare.",
        "Just close" to "Chiudi e basta",
        "Thank you!" to "Grazie!",
        "You credited" to "Hai assegnato a",
        "rescued" to "salvati"
    )
}

fun tr(vm: Vm, k: String): String {
    if (vm.lang == "IT") {
        return Str.it[k] ?: k
    }
    return k
}

fun emoji(c: String): String = when (c) {
    "FOOD" -> "🍲"
    "CLOTH" -> "🧥"
    "HYG" -> "🧴"
    "BABY" -> "🍼"
    "SCHOOL" -> "📚"
    else -> "📦"
}

fun cname(c: String): String = when (c) {
    "FOOD" -> "Food"
    "CLOTH" -> "Clothes"
    "HYG" -> "Hygiene"
    "BABY" -> "Baby"
    "SCHOOL" -> "School"
    else -> "Other"
}
